version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /app/desktop
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /app/frontend
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /app/restful
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /app/worker
    schedule:
      interval: daily