version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /desktop
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /proton
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/sdk
    schedule:
      interval: daily