version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /app/backend
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /proton
    schedule:
      interval: daily
