version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/proton
    schedule:
        interval: daily
  - package-ecosystem: dart
    directory: /proton
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
        interval: daily
