tasks:
  - init: |
      sudo apt update -y && sudo apt upgrade -y
      rustup default nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      cargo install --locked trunk
      cargo install wasm-bindgen-cli
      npm install -g npm@8.19.2 && npm install && cargo install create-tauri-app
      sudo apt install -y \
          libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
    command: cargo build --workspace


