tasks:
  - init: |
      sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt install -y protobuf-compiler
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      rustup component add clippy rustfmt --toolchain nightly
    command: cargo run -- system --up


