tasks:
  - init: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      rustup uninstall stable && rustup default nightly && rustup install stable && rustup target add wasm32-unknown-unknown --toolchain nightly
      npm install -g npm@8.19.2 && npm install
      sudo apt install -y \
          libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
      cargo install create-tauri-app
    command: npm run build


