[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
categories = ["binary", "gui"]
description = ""
edition = "2021"
keywords = ["gui"]
license = "MIT"
name = "proton"
repository = "https://github.com/scattered-systems/proton.git"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
config = "0.13.1"
druid = "0.7.0"
glob = "0.3.0"