[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Proton "
edition = "2021"
homepage = "https://scattered-systems.github.io/proton/"
keywords = []
license = "MIT"
name = "proton"
readme = "README.md"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.1"

[[bin]]
bench = false
name = "proton"

[build-dependencies]

[dependencies]
druid = { features = ["image-all", "webp"], version = "0.7.0" }
scsys = { features = ["full"], path = "../../crates/scsys", version = ">=0.1.3" }

[dev-dependencies]
