

pipelines:
  rustup:
    default: nightly
    flags:
    commands:
      component:
        add:
          - clippy
          - rustfmt
      target:
        - wasm32-unknown-unknown
        - wasm32-wasi
      toolchain: [ "nightly" ]
  sudo:
    flags: [ "-y" ]
    commands: 
      install:
        - libgtk-3-dev
        - libwebkit2gtk-4.0-dev
        - libappindicator3-dev
        - librsvg2-dev-
        - patchelf
        - protobuf-compiler
