[application]
asset_dir = "static"
default_platform = "web"
name = "Proton"
out_dir = "dist"

[application.plugins]
available = true
required = []

[application.tools]

[web.app]

title = "Proton"

[web.resource]

style = [
    "css/app.css",
    "css/tailwind.min.css",
    "https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css",
    "https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"
]
script = [
    "https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"
]

[web.resource.dev]
script = []

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "static"]
