[build]
dist = "dist"
target = "public/index.html"

[serve]
address = "0.0.0.0"
no_autoreload = false
open = false
port = 8080

[tools]
wasm_bindgen = "0.2.86"
wasm_opt = "version_110"

# [[hooks]]
# stage = "pre_build"
# command = "bash"
# command_arguments = ["-c", "npm run webpack:build"]
