[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "proton"
edition = "2021"
homepage = "https://github.com/scattered-systems/proton/wiki"
keywords = []
license = "Apache-2.0"
name = "proton"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[[bin]]
bench = true
name = "proton"
path = "src/main.rs"
test = false

[build-dependencies]

[dependencies]
acme = { features = ["net"], git = "https://github.com/FL03/acme", branch = "v0.2.5", version = "0.2.5" }
proton-sdk = { features = ["full"], path = "../crates/sdk", version = "0.1.0" }
scsys = { features = [], version = "0.1.40" }

async-session = "3.0.0"
async-trait = "0.1.60"
axum = { features = ["headers", "http2", "macros", "ws"], version = "0.6" }
clap = { features = ["derive"], version = "4" }
ethers = { features = [], version = "1" }
futures = "0.3"
http = "0.2"
hyper = { features = [], version = "0.14" }
oauth2 = "4.3.0"
redis = { features = ["tokio"], version = "0.22.1" }
reqwest = { features = ["json", "rustls-tls", "stream"], version = "0.11.13" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
siwe = "0.5"
strum = { features = ["derive"], version = "0.24.1" }
tokio = { features = ["full"], version = "1" }
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3" }
tracing = "0.1.37"
tracing-subscriber = { features = ["env-filter"], version = "0.3" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
