[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
build = "build.rs"
categories = []
description = "Proton is a personal computing platform powered by the scsys ecosystem"
edition = "2021"
keywords = ["wasm"]
license = "MIT"
name = "proton"
readme = "README.md"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[features]
default = ["core"]
full = ["core"]

core = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dependencies]
# algae = { features = ["full"], git = "https://github.com/scattered-systems/algae", version = "0.1.13" }
chrono = "0.4.23"
console_error_panic_hook = { optional = true, version = "0.1.7" }
dotenv_codegen = "0.15.0"
futures = "0.3.25"
gloo = "0.8.0"
js-sys = "0.3.60"
lazy_static = "1.4.0"
lru = "0.8.1"
parking_lot = "0.12.1"
pulldown-cmark = "0.9.2"
scsys = { git = "https://github.com/scattered-systems/scsys", branch="v0.1.28", version = "0.1.28" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
tokio = "1.22.0"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"

[dependencies.web-sys]
features = [
    "AddEventListenerOptions",
    "Event",
    "EventListener",
    "EventListenerOptions",
    "FetchEvent",
    "FetchEventInit",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window"
]
version = "0.3.60"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[target.wasm32-unknown-unknown]

