[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
categories = []
description = "Proton is a personal computing platform powered by the scsys ecosystem"
edition = "2021"
keywords = ["wasm"]
license = "Apache-2.0"
name = "proton"
readme = "README.md"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[features]
default = []
full = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[[bin]]
name = "proton"

[build-dependencies]

[dev-dependencies]

[dependencies]
async-session = "3.0.0"
axum = { features = ["headers", "http2", "ws"], version = "0.6.0" }
clap = { features = ["derive"], version = "4.0.27" }
futures = "0.3.25"
glob = "0.3.0"
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.23" }
lru = "0.8.1"
reqwest = { features = ["json", "rustls-tls", "stream"], version = "0.11.13" }
scsys = { features = ["full"], version = "0.1.33" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.89"
strum = { features = ["derive"], version = "0.24.1" }
tarpc = { features = [], version = "0.31.0" }
tokio = { features = ["full"], version = "1.22.0" }
tokio-stream = "0.1.11"
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3.4" }
tracing = "0.1.37"
tracing-subscriber = { features =["env-filter"], version = "0.3.16" }
wasmer = { features = [], version = "3.0.1" }

