[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
description = ""
edition = "2021"
license = "MIT"
name = "proton"
repository = "https://github.com/scattered-systems/proton.git"
version = "0.1.0"

[dependencies]
acme = "0.1.8"
chrono = "0.4.19"
config = "0.13.1"
glob = "0.3.0"