[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Proton "
edition = "2021"
homepage = "https://github.com/scattered-systems/proton"
keywords = []
name = "proton"
readme = "README.md"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[[bin]]
bench = false
name = "proton"

[dependencies]

[dev-dependencies]

[build-dependencies]

