[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Proton is designed to be the heart of the ecosystem, securely delivering all visual expeiences"
edition = "2021"
homepage = "https://scattered-systems.github.io/proton/"
keywords = []
license = "MIT"
name = "proton"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[[bin]]
bench = false
name = "proton"
test = false

[build-dependencies]

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
config = "0.13.1"
druid = { features = ["image-all", "webp"], version = "0.7.0" }
scsys = { features = ["full"], version = "0.1.7" }
serde = { features = ["derive"], version = "1.0.139" }
serde_json = "1.0.82"
siwe = "0.4.0"
web3 = "0.18.0"

[dependencies.protonic]
features = ["full"]
optional = false
path = "../../lib/protonic"
version = "0.1.2"


[dev-dependencies]
