version: "4"
services:
  proton:
      build:
        context: ../proton
        dockerfile: Dockerfile
      container_name: proton
      ports:
        - "8000:8000"
      restart: always
      volumes:
        - /config:/config
        - /data:/data
  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - /data/postgres:/var/lib/postgresql/data
  
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  config:
  data:
  