version: "4"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ../.config:/config
      - /data:/data
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ../.config:/config
      - /data:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - /data/postgres:/var/lib/postgresql/data

volumes:
  config:
  data:
  