[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
categories = []
description = "Proton is a personal computing platform powered by the scsys ecosystem"
edition = "2021"
keywords = ["wasm"]
license = "Apache-2.0"
name = "proton-core"
repository = "https://github.com/scattered-systems/proton"
version = "0.1.0"

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
gloo = "0.8.0"
js-sys = { features = [], version = "0.3.60" }
serde = { features = ["derive"], version = "1.0.149" }
serde_json = "1.0.89"
strum = { features = ["derive"], version = "0.24.1" }
wasm-bindgen = { features = ["serde-serialize"], version = "0.2.83" }
wasm-bindgen-futures = "0.4.33"

[dependencies.web-sys]
features = []
version = "0.3.60"