name: 'Desktop'

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
  schedule:
    - cron: "30 9 * * 5"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: environment
      release:
        default: true
        description: 'Release'
        required: true
        type: boolean

jobs:
  constructor:
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.constructor.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              configPath: 'desktop/tauri.conf.json',
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `proton-v${process.env.PACKAGE_VERSION}`,
              name: `Proton v${process.env.PACKAGE_VERSION}`,
              body: 'View the assets bundled below to find a suitable installer for your host system',
              draft: true,
              prerelease: false
            })
            return data.id
  builder:
    needs: constructor
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: rust (stable)
        uses: dtolnay/rust-toolchain@stable
      - name: langspace
        run: cargo xtask langspace
      - name: configure environment (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: trunk build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.constructor.outputs.release_id }}

  release:
    needs: [ builder, constructor ]
    runs-on: ubuntu-20.04
    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.constructor.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              configPath: 'desktop/tauri.conf.json',
              draft: false,
              prerelease: ${{ github.event.inputs.release }},
              owner: context.repo.owner,
              release_id: process.env.release_id,
              repo: context.repo.repo
            })
