name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * 5"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown
          - wasm32-wasi
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target }} --toolchain nightly
      - run: cargo build -v --release --workspace --target ${{ matrix.target }}
      - run: cargo test --all --all-features -v --target ${{ matrix.target }}
  features:
    if: ${{ github.event.inputs.publish }}
    needs: [ build ]
    name: Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - proton-core
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target }} --toolchain nightly
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  sdk:
    if: ${{ github.event.inputs.publish }}
    name: Features
    needs: [ build, features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (proton-sdk)
        run: cargo publish --all-features -v -p proton-sdk --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  apps:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: [ build, sdk ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - proton-desktop
          - proton
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{ matrix.package }})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  