name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches-ignore: [ "beta*", "dev*", "next*" ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
      types: [created]
  schedule:
    - cron: "30 9 * * *" # 9:30am UTC
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ wasm32-unknown-unknown, wasm32-wasi ]
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target }} --toolchain nightly
      - name: Build
        run: cargo build --release -v --target ${{ matrix.target }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            target/${{ matrix.target }}/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-master
  